# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MGS.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


#class QtyWindow(QWidget):


class Ui_HomeWindow(object):
        
    def setupUi(self, MainWindow):
        #identify screen size
        sizeObject = QtWidgets.QDesktopWidget().screenGeometry(0)
        scrn_height = sizeObject.height()
        scrn_width = sizeObject.width()
        # Window Screen Set-up
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(scrn_width, scrn_height)


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.lbl_searchItem = QtWidgets.QLabel(self.centralwidget)
        self.lbl_searchItem.setGeometry(QtCore.QRect(40, 40, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_searchItem.setFont(font)
        self.lbl_searchItem.setObjectName("lbl_searchItem")

        self.lineEdit_search = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_search.setGeometry(QtCore.QRect(180, 50, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_search.setFont(font)
        self.lineEdit_search.setObjectName("lineEdit_search")

        self.lbl_itemCode = QtWidgets.QLabel(self.centralwidget)
        self.lbl_itemCode.setGeometry(QtCore.QRect(700, 40, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        self.lbl_itemCode.setFont(font)
        self.lbl_itemCode.setObjectName("lbl_itemCode")
        
        self.lineEdit_iCode = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_iCode.setGeometry(QtCore.QRect(930, 40, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_iCode.setFont(font)
        self.lineEdit_iCode.setObjectName("lineEdit_iCode")
        
        self.lbl_itemName = QtWidgets.QLabel(self.centralwidget)
        self.lbl_itemName.setGeometry(QtCore.QRect(700, 120, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        self.lbl_itemName.setFont(font)
        self.lbl_itemName.setObjectName("lbl_itemName")

        self.lineEdit_iName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_iName.setGeometry(QtCore.QRect(930, 120, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_iName.setFont(font)
        self.lineEdit_iName.setObjectName("lineEdit_iName")
        
        self.lbl_purQty = QtWidgets.QLabel(self.centralwidget)
        self.lbl_purQty.setGeometry(QtCore.QRect(700, 200, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_purQty.setFont(font)
        self.lbl_purQty.setObjectName("lbl_purQty")
        
        self.lineEdit_pQty = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pQty.setGeometry(QtCore.QRect(930, 200, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setPointSize(18)
        self.lineEdit_pQty.setFont(font)
        self.lineEdit_pQty.setObjectName("lineEdit_pQty")
        
        self.lbl_itemPrice = QtWidgets.QLabel(self.centralwidget)
        self.lbl_itemPrice.setGeometry(QtCore.QRect(700, 280, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        self.lbl_itemPrice.setFont(font)
        self.lbl_itemPrice.setObjectName("lbl_itemPrice")
        
        self.lineEdit_iPrice = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_iPrice.setGeometry(QtCore.QRect(930, 280, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setPointSize(18)
        self.lineEdit_iPrice.setFont(font)
        self.lineEdit_iPrice.setObjectName("lineEdit_iPrice")
        
        self.lbl_subTotal = QtWidgets.QLabel(self.centralwidget)
        self.lbl_subTotal.setGeometry(QtCore.QRect(700, 360, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        self.lbl_subTotal.setFont(font)
        self.lbl_subTotal.setObjectName("lbl_subTotal")
        
        self.lineEdit_sTotal = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_sTotal.setGeometry(QtCore.QRect(930, 360, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_sTotal.setFont(font)
        self.lineEdit_sTotal.setObjectName("lineEdit_sTotal")
        
        self.lbl_total = QtWidgets.QLabel(self.centralwidget)
        self.lbl_total.setGeometry(QtCore.QRect(700, 440, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        self.lbl_total.setFont(font)
        self.lbl_total.setObjectName("lbl_total")
        
        self.lineEdit_total = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_total.setGeometry(QtCore.QRect(930, 440, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_total.setFont(font)
        self.lineEdit_total.setObjectName("lineEdit_total")
        
        self.btn_payout = QtWidgets.QPushButton(self.centralwidget)
        self.btn_payout.setGeometry(QtCore.QRect(850, 590, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_payout.setFont(font)
        self.btn_payout.setObjectName("btn_payout")
        
        self.btn_discard = QtWidgets.QPushButton(self.centralwidget)
        self.btn_discard.setGeometry(QtCore.QRect(1000, 590, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_discard.setFont(font)
        self.btn_discard.setObjectName("btn_discard")
        
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(1150, 590, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(510, 50, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        self.btn_search.setFont(font)
        self.btn_search.setObjectName("btn_search")
        
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setGeometry(QtCore.QRect(700, 590, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_next.setFont(font)
        self.btn_next.setObjectName("btn_next")

        self.tableWidget_purchasedItems = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_purchasedItems.setGeometry(QtCore.QRect(40, 110, 561, 541))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.tableWidget_purchasedItems.setFont(font)
        self.tableWidget_purchasedItems.setObjectName("tableWidget_purchasedItems")
        #col/row counts of tableWidget
        self.tableWidget_purchasedItems.setColumnCount(5)
        self.tableWidget_purchasedItems.setRowCount(1)
        #set column names of tableWidget
        colName_lst = ['Item Code', 'Item Name', 'Qty','Price', 'Amount']
        self.tableWidget_purchasedItems.setHorizontalHeaderLabels(colName_lst)
        #self.tableWidget_purchasedItems.setHorizontalHeaderLabels(list('Item Code','Item Name', 'Qty','Price', 'Amount'))
        #removing of row gridlines of tableWidget
        self.tableWidget_purchasedItems.setShowGrid(False)
        self.tableWidget_purchasedItems.setStyleSheet('QTableView::item {border-right: 1px solid #d6d9dc;}')
        #setting up column width of tableWidget
        self.tableWidget_purchasedItems.setColumnWidth(0,90)
        self.tableWidget_purchasedItems.setColumnWidth(1,260)
        self.tableWidget_purchasedItems.setColumnWidth(2,50)
        self.tableWidget_purchasedItems.setColumnWidth(3,70)
        self.tableWidget_purchasedItems.setColumnWidth(4,70)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        
        self.mb_File = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.mb_File.setFont(font)
        self.mb_File.setObjectName("mb_File")
        
        self.mb_View = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.mb_View.setFont(font)
        self.mb_View.setObjectName("mb_View")
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.file_Close = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.file_Close.setFont(font)
        self.file_Close.setObjectName("file_Close")
        
        self.view_Inventory = QtWidgets.QAction(MainWindow)
        self.view_Inventory.setObjectName("view_Inventory")
        
        self.edit_modItem = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.edit_modItem.setFont(font)
        self.edit_modItem.setObjectName("edit_modItem")
        
        self.mb_File.addAction(self.file_Close)
        self.mb_View.addAction(self.view_Inventory)
        self.mb_View.addAction(self.edit_modItem)
        self.menubar.addAction(self.mb_File.menuAction())
        self.menubar.addAction(self.mb_View.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_itemName.setText(_translate("MainWindow", "Item Name:"))
        self.lbl_purQty.setText(_translate("MainWindow", "Quantity:"))
        self.lbl_itemPrice.setText(_translate("MainWindow", "Item Price:"))
        self.lbl_subTotal.setText(_translate("MainWindow", "Sub Total:"))
        self.lbl_total.setText(_translate("MainWindow", "Total Amount:"))
        self.btn_payout.setStatusTip(_translate("MainWindow", "Print Receipt"))
        self.btn_payout.setText(_translate("MainWindow", "Payout"))
        self.btn_discard.setStatusTip(_translate("MainWindow", "Remove current item"))
        self.btn_discard.setText(_translate("MainWindow", "Discard"))
        self.btn_cancel.setStatusTip(_translate("MainWindow", "Cancel all purchased items"))
        self.btn_cancel.setText(_translate("MainWindow", "Cancel"))
        self.lbl_itemCode.setText(_translate("MainWindow", "Item Code:"))
        self.lbl_searchItem.setText(_translate("MainWindow", "Search Item:"))
        self.btn_search.setStatusTip(_translate("MainWindow", "Search for an Item"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        self.btn_next.setStatusTip(_translate("MainWindow", "Add item to Purchase"))
        self.btn_next.setText(_translate("MainWindow", "Next"))
        self.mb_File.setTitle(_translate("MainWindow", "File"))
        self.mb_View.setTitle(_translate("MainWindow", "View"))
        self.file_Close.setText(_translate("MainWindow", "Close"))
        self.file_Close.setStatusTip(_translate("MainWindow", "Close Application"))
        self.file_Close.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.view_Inventory.setText(_translate("MainWindow", "View Inventory"))
        self.view_Inventory.setStatusTip(_translate("MainWindow", "View Item Inventory"))
        self.view_Inventory.setShortcut(_translate("MainWindow", "Ctrl+Shift+I"))
        self.edit_modItem.setText(_translate("MainWindow", "Modify Item"))
        self.edit_modItem.setStatusTip(_translate("MainWindow", "Modify Item"))
        self.edit_modItem.setShortcut(_translate("MainWindow", "Ctrl+Shift+E"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     HomeWindow = QtWidgets.QMainWindow()
#     ui_home = Ui_HomeWindow()
#     ui_home.setupUi(HomeWindow)
#     HomeWindow.show()
#     sys.exit(app.exec_())
