# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payout.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PayoutForm(object):
    def setupUi(self, PayoutForm):
        PayoutForm.setObjectName("PayoutForm")
        PayoutForm.resize(323, 237)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        PayoutForm.setFont(font)

        self.lineEdit_cash = QtWidgets.QLineEdit(PayoutForm)
        self.lineEdit_cash.setGeometry(QtCore.QRect(140, 70, 161, 23))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_cash.setFont(font)
        self.lineEdit_cash.setObjectName("lineEdit_cash")

        self.lbl_cash = QtWidgets.QLabel(PayoutForm)
        self.lbl_cash.setGeometry(QtCore.QRect(10, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.lbl_cash.setFont(font)
        self.lbl_cash.setObjectName("lbl_cash")

        self.lbl_amount = QtWidgets.QLabel(PayoutForm)
        self.lbl_amount.setGeometry(QtCore.QRect(10, 30, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.lbl_amount.setFont(font)
        self.lbl_amount.setObjectName("lbl_amount")
        
        self.lineEdit_total = QtWidgets.QLineEdit(PayoutForm)
        self.lineEdit_total.setGeometry(QtCore.QRect(140, 30, 161, 23))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_total.setFont(font)
        self.lineEdit_total.setObjectName("lineEdit_total")

        self.lbl_change = QtWidgets.QLabel(PayoutForm)
        self.lbl_change.setGeometry(QtCore.QRect(10, 110, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.lbl_change.setFont(font)
        self.lbl_change.setObjectName("lbl_change")

        self.lineEdit_change = QtWidgets.QLineEdit(PayoutForm)
        self.lineEdit_change.setGeometry(QtCore.QRect(140, 110, 161, 23))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_change.setFont(font)
        self.lineEdit_change.setObjectName("lineEdit_change")

        self.btn_print = QtWidgets.QPushButton(PayoutForm)
        self.btn_print.setGeometry(QtCore.QRect(50, 170, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_print.setFont(font)
        self.btn_print.setObjectName("btn_print")

        self.btn_cancel = QtWidgets.QPushButton(PayoutForm)
        self.btn_cancel.setGeometry(QtCore.QRect(180, 170, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(PayoutForm)
        QtCore.QMetaObject.connectSlotsByName(PayoutForm)

    def retranslateUi(self, PayoutForm):
        _translate = QtCore.QCoreApplication.translate
        PayoutForm.setWindowTitle(_translate("PayoutForm", "Payout Form"))
        self.lbl_amount.setText(_translate("PayoutForm", "Total Amount:"))
        self.lbl_cash.setText(_translate("PayoutForm", "Cash:"))
        self.lbl_change.setText(_translate("PayoutForm", "Change:"))
        self.btn_print.setText(_translate("PayoutForm", "Print"))
        self.btn_cancel.setText(_translate("PayoutForm", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PayoutForm = QtWidgets.QDialog()
    ui = Ui_PayoutForm()
    ui.setupUi(PayoutForm)
    PayoutForm.show()
    sys.exit(app.exec_())
