# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QtyWindow(object):

    def setupUi(self, window):
        window.setObjectName("Quantity")
        window.resize(333, 180)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_quantity = QtWidgets.QLabel(self.centralwidget)
        self.lbl_quantity.setGeometry(QtCore.QRect(30, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.lbl_quantity.setFont(font)
        self.lbl_quantity.setObjectName("lbl_quantity")
        self.lineEdit_Qty = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Qty.setGeometry(QtCore.QRect(120, 40, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Qty.setFont(font)
        self.lineEdit_Qty.setObjectName("lineEdit_Qty")

        self.btn_ok = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ok.setGeometry(QtCore.QRect(60, 100, 80, 23))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        self.btn_ok.setFont(font)
        self.btn_ok.setObjectName("btn_ok")


        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(180, 100, 80, 23))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 333, 20))
        self.menubar.setObjectName("menubar")
        window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("Quantity", "Item Quantity"))
        self.lbl_quantity.setText(_translate("Quantity", "Quantity:"))
        self.btn_ok.setText(_translate("Quantity", "OK"))
        self.btn_cancel.setText(_translate("Quantity", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    qty_win = QtWidgets.QMainWindow()
    ui = Ui_QtyWindow()
    ui.setupUi(qty_win)
    qty_win.show()
    sys.exit(app.exec_())
